version: "3.9"
services:
  caddy:
    image: caddy:latest
    container_name: caddy
    volumes:
      - $BASE_DIR/apps/caddy/config:/etc/caddy
      - $BASE_DIR/apps/caddy/static:/var/www/html:ro
      - $BASE_DIR/certs:/etc/certs/ssl:ro
    restart: unless-stopped
