version: "3.3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    expose:
      - 9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
        traefik.enable: true
        traefik.http.routers.portainer.rule: "Host(`htd-bizapps-monitor.cisco.com`)"
        traefik.http.routers.portainer.entrypoints: "https"
        traefik.http.routers.portainer.tls: true
        traefik.http.routers.portainer.service: "portainer"
        traefik.http.services.portainer.loadbalancer.server.port: 9000


volumes:
  portainer_data:
