version: "3.9"
services:
  mail:
    image: bytemark/smtp
    restart: always
    
  plausible_db:
    image: postgres:12
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - $BASE_DIR/apps/plausible/config/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - $BASE_DIR/apps/plausible/config/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    container_name: plausible
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    expose:
      - 8000
    env_file:
      - $BASE_DIR/apps/plausible/config/conf.env
    labels:
        traefik.enable: true
        traefik.http.routers.plausible.rule: "Host(`htd-bizapps-monitor.cisco.com`)"
        traefik.http.routers.plausible.entrypoints: "https"
        traefik.http.routers.plausible.tls: true
        traefik.http.routers.plausible.service: "plausible"
        traefik.http.services.plausible.loadbalancer.server.port: 8000

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
